# Generated by Django 3.1.2 on 2020-10-19 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_type', models.CharField(db_index=True, max_length=50, verbose_name='Тип оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('shop', models.CharField(max_length=250, verbose_name='Магазин')),
                ('what_buy', models.TextField(blank=True, verbose_name='Что купить?')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('personal_info', models.BooleanField(default=True, verbose_name='Принимаю условия обработки персональных данных ')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delivery_form.payment', verbose_name='Оплата')),
            ],
        ),
    ]
